# Generated by Django 3.0.8 on 2020-07-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='keyword',
            field=models.TextField(default='123'),
            preserve_default=False,
        ),
    ]
