# Generated by Django 3.0.8 on 2020-07-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200725_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='slug',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
