# Generated by Django 3.0.8 on 2020-08-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_technology_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
